Within the `client` directory, edit the file `src/App.vue` as shown below:

.client/src/App.vue
[source,javascript]
----
include::{sourceDir}/client/src/App.vue[indent=0]
----
<1> Add `Micronaut` component to template
<2> Import `Micronaut` component
<3> Declare `Micronaut` component

Now create a `Micronaut.vue` file in the `client/src/components` folder as shown below:

.client/src/components/Micronaut.vue
[source,javascript]
----
include::{sourceDir}/client/src/components/Micronaut.vue[indent=0]
----
<1> Form to accept the user's name
<2> Conditionally display message from the server
<3> Define some initial state
<4> Method to make a request to the server to retrieve the "Hello" message and reactively update the `message` data property 

The `SERVER_URL` variable used in the above component needs to be defined in a configuration file. Create the file `config.js` within the `client/src` directory, and add the following content:

[source,javascript]
----
include::{sourceDir}/client/src/config.js[indent=0]
----
<1> Use the current Node environment to determine which URL to use for server requests
