micronaut:
  application:
    name: server
---
#tag::cors[]
micronaut:
  server:
    cors:
      enabled: true
#end::cors[]
---
#tag::staticResources[]
micronaut:
  router:
    static-resources:
      default:
        enabled: true   #<1>
        mapping: "/**"  #<2>
        paths: "classpath:public" #<3>
#end::staticResources[]